version: "3.9"
services:
  my-sql:
    container_name: my-sql
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: xizot
      MYSQL_PASSWORD: xizot
    volumes:
      - E:/db/mysql:/var/lib/mysql
    restart: unless-stopped